### ISSUE TITLE
Error while executing the program

### ISSUE THREAD

**Issue by marcomarson** [erivandoramos/TwoRC522RPi#4]
I keep getting some messages while executing the program and can't read the cards.

GPIO v.0.6.3
Thread LeitorCartao. Run..
RFID_RC522 ( Module 01)
RFID_RC522(Module 02)
SPI closed!
RFID_RC522 ( Module 01)
RFID_RC522(Module 02)
SPI closed!

And it keeps on repeting the last 3 lines. How can I fix that?
Thank you

**Comment by marcomarson** [comment]
I fixed this issue. I will close it

**Comment by ravilak** [comment]
How did you fix this? I am going through the same issue?
